# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
