# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='professor',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='new_employer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
